name: remisse_arequipa_driver
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.1.4
  firebase_database: ^11.0.4
  intl_phone_field: ^3.2.0
  connectivity_plus: ^6.0.4
  google_maps_flutter: ^2.8.0
  firebase_core: ^3.3.0
  change_app_package_name: ^1.3.0
  permission_handler: ^11.3.1
  geolocator: ^12.0.0
  firebase_storage: ^12.1.3
  google_maps_flutter_ios: ^2.12.0  
  flutter_geofire: ^2.0.3
  http: ^1.2.2
  flutter_polyline_points: ^2.1.0
  restart_app: ^1.2.1
  firebase_messaging: ^15.0.4
  assets_audio_player: ^3.1.1
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  geocoding: ^3.0.0
  google_places_flutter: ^2.0.9
  intl: ^0.19.0
  path_provider: ^2.1.4
  image: ^4.2.0
  flutter_image_compress: ^2.3.0
  sizer: ^2.0.15
  iconly: ^1.0.1
  animate_do: ^3.0.2
  lottie: ^3.1.2
  animated_splash_screen: ^1.3.0
  flutter_native_splash: ^2.4.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - lib/assets/google.png
    - lib/assets/MeganProfile.jpg
    - lib/assets/profileuser.png
    - lib/assets/avatarman.png
    - lib/assets/final.png
    - lib/assets/initial.png
    - lib/assets/totalearnings.png
    - lib/assets/totaltrips.png
    - lib/assets/tracking.png
    - lib/assets/tripscompleted.png
    - lib/assets/uberexec.png
    - lib/assets/night_style.json
    - lib/assets/logo.png
    - lib/assets/loginImage.png
    - lib/assets/splash.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
